# Generated by Django 5.0.6 on 2024-06-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
